version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:17"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:27"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:37"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:47"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
