"""
Django settings for backupsheep project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import io
import json
import os
from pathlib import Path
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
import google.auth
from dotenv import load_dotenv
from dotenv import dotenv_values

# Build paths inside the project like this: BASE_DIR / 'subdir'.
ROOT_PATH = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.dirname(os.path.dirname(__file__))

# Local working directory for in-progress backups and their logs. Backup tasks run
# with the project root as CWD (see supervisor config), so this resolves to the same
# place as the relative "_storage/" paths they use; ensure it exists.
os.makedirs(os.path.join(BASE_DIR, "_storage"), exist_ok=True)

if "BACKUPSHEEP_SECRETS" in os.environ:
    config = json.loads(os.environ.get("BACKUPSHEEP_SECRETS"))
else:
    config = {
        **dotenv_values(".env"),  # load shared development variables
        **os.environ,  # override loaded values with environment variables
    }

# Coerce env strings to real booleans: dotenv/docker env_file always yield strings, and
# a bare bool("false") is True, so a raw string can never be turned off. Treat only the
# obvious truthy spellings as on.
def _as_bool(value, default=False):
    if isinstance(value, bool):
        return value
    if value is None:
        return default
    return str(value).strip().lower() in ("1", "true", "yes", "on")


SECRET_KEY = config["DJANGO_SECRET_KEY"]
DEBUG = _as_bool(config.get("DJANGO_DEBUG", "false"))
DJANGO_SERVER = config["DJANGO_SERVER"]
# Accepts one host or a comma-separated list, e.g. "backup.example.com,www.example.com".
ALLOWED_HOSTS = [h.strip() for h in str(config["DJANGO_ALLOWED_HOSTS"]).split(",") if h.strip()]
CSRF_TRUSTED_ORIGINS = [f"{config['APP_PROTOCOL']}{config['APP_DOMAIN']}"]

# HTTPS / production hardening. Set DJANGO_HTTPS=true once this install is served over TLS
# (typically a reverse proxy that terminates HTTPS and forwards X-Forwarded-Proto). Left
# off by default so a plain-HTTP localhost/dev install isn't locked out by Secure cookies
# or an HTTP->HTTPS redirect loop.
HTTPS_ENABLED = _as_bool(config.get("DJANGO_HTTPS", "false"))
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_CONTENT_TYPE_NOSNIFF = True
if HTTPS_ENABLED:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "rest_framework",
    "rest_framework.authtoken",
    "django.contrib.humanize",
    "django_user_agents",
    "django_filters",
    "django_celery_results",
    "django_celery_beat",
    'apps',

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Serve static files directly from gunicorn (no nginx in the container).
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_user_agents.middleware.UserAgentMiddleware",
    "utils.middleware.TimezoneMiddleware",
    # Forces a not-yet-configured install into the first-run wizard (and locks it
    # afterward). Must run before RedirectMiddleware so onboarding wins over login.
    "utils.middleware.OnboardingMiddleware",
    "utils.middleware.RedirectMiddleware",

]

ROOT_URLCONF = "backupsheep.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR + "/apps/console/_templates/",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "debug": DEBUG,
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.static",
                "django.template.context_processors.media",
                "django.template.context_processors.tz",
                "django.template.context_processors.i18n",
                "utils.context_processors.timezone",
                "utils.context_processors.site",
            ],
        },
    },
]

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "core_cache",
    }
}

WSGI_APPLICATION = "backupsheep.wsgi.application"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "apps.api.v1.utils.api_authentication.ConsoleSessionAuthentication",
        "apps.api.v1.utils.api_authentication.CustomTokenAuthentication",
    ),
    # The browsable API UI is handy in development but exposes a self-documenting,
    # form-driven interface in production, so only enable it when DEBUG is on.
    "DEFAULT_RENDERER_CLASSES": (
        ("rest_framework.renderers.JSONRenderer",)
        + (("rest_framework.renderers.BrowsableAPIRenderer",) if DEBUG else tuple())
    ),
    "EXCEPTION_HANDLER": "rest_framework.views.exception_handler",
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
    ),
}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
MIGRATION_MODULES = {"apps": "apps._migrations"}

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config["DB_NAME"],
        "USER": config["DB_USER"],
        "PASSWORD": config["DB_PASSWORD"],
        "HOST": config["DB_HOST"],
        "PORT": config["DB_PORT"],
    },
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True
DATETIME_FORMAT = '%d-%m-%Y %H:%M:%S'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
)

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR + "/static/"

STATICFILES_DIRS = (
    ("console", BASE_DIR + "/apps/console/_static/console"),
)

# WhiteNoise serves collected static files from gunicorn (no nginx in the container).
# CompressedStaticFilesStorage gzips assets but does not hash filenames, so it never
# errors on a {% static %} reference whose file is missing from STATIC_ROOT.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# App Settings
APP_NAME = config["APP_NAME"]
APP_DOMAIN = config["APP_DOMAIN"]
APP_PROTOCOL = config["APP_PROTOCOL"]
APP_URL = f"{APP_PROTOCOL}{APP_DOMAIN}"

sentry_sdk.init(
    dsn=config["SENTRY_DSN"],
    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    traces_sample_rate=1.0,
    # Set profiles_sample_rate to 1.0 to profile 100%
    # of sampled transactions.
    # We recommend adjusting this value in production.
    profiles_sample_rate=1.0,
    integrations=[
        DjangoIntegration(
            transaction_style='url',
            middleware_spans=True,
            signals_spans=False,
            cache_spans=False,
        ),
    ],
    environment=DJANGO_SERVER
)

HOME_URL = "/console"
LOGIN_URL = "/login"
API_PATH = "/api/"
CONSOLE_URL = "/console"
ONBOARDING_URL = "/onboarding"

# First-run onboarding gate. Whoever completes the wizard becomes the instance admin,
# so creating the first account requires proof of infrastructure access: either this
# fixed token from the environment, or a per-install random token the app writes to
# ONBOARDING_INSTALL_TOKEN_FILE (read it with:
#   docker compose exec app cat /code/_storage/install_token
# ). Without the gate, anyone who reaches an unconfigured install over the network
# could claim the admin account before the real operator does.
ONBOARDING_INSTALL_TOKEN = config.get("ONBOARDING_INSTALL_TOKEN", "")
ONBOARDING_INSTALL_TOKEN_FILE = os.path.join(BASE_DIR, "_storage", "install_token")

LOGIN_REQUIRED_IGNORE_PATHS = [
    r'/login',
    r'/reset',
    r'/django-admin/',
    r'/api/',
    r'/error/',
    r'/onboarding',
]

# POSTMARK - Email Service
POSTMARK_API_KEY = config["POSTMARK_API_KEY"]
POSTMARK_DOMAIN = config["POSTMARK_DOMAIN"]
POSTMARK_EMAIL = config["POSTMARK_EMAIL"]
POSTMARK_API_URL = config["POSTMARK_API_URL"]

# AWS SES - Email Service
SES_REGION_NAME = config["SES_REGION_NAME"]
SES_REGION_ENDPOINT = config["SES_REGION_ENDPOINT"]
SES_ACCESS_KEY_ID = config["SES_ACCESS_KEY_ID"]
SES_SECRET_ACCESS_KEY = config["SES_SECRET_ACCESS_KEY"]

# MAILGUN - Email Service
MAILGUN_DOMAIN = config["MAILGUN_DOMAIN"]
MAILGUN_EMAIL = config["MAILGUN_EMAIL"]
MAILGUN_API_KEY = config["MAILGUN_API_KEY"]
MAILGUN_API_URL = config["MAILGUN_API_URL"]

# Options are postmark, mailgun and ses
EMAIL_PROVIDER = config["EMAIL_PROVIDER"]

# Storage to be used for application logs etc. Tested with AWS S3 and Cloudflare R2
S3_ACCESS_KEY_ID = config["S3_ACCESS_KEY_ID"]
S3_SECRET_ACCESS_KEY = config["S3_SECRET_ACCESS_KEY"]
S3_STORAGE_BUCKET_NAME = config["S3_STORAGE_BUCKET_NAME"]
S3_ENDPOINT_URL = config["S3_ENDPOINT_URL"]
S3_SIGNATURE_VERSION = config["S3_SIGNATURE_VERSION"]

# Dropbox Storage - Create Dropbox App and add keys in .env file
# Learn more: https://www.dropbox.com/developers/reference/getting-started#app%20console
DROPBOX_APP_KEY = config["DROPBOX_APP_KEY"]
DROPBOX_APP_SECRET = config["DROPBOX_APP_SECRET"]


# OneDrive Storage
MS_CLIENT_ID = config["MS_CLIENT_ID"]
MS_OBJECT_ID = config["MS_OBJECT_ID"]
MS_TENANT_ID = config["MS_TENANT_ID"]
MS_APPLICATION_ID = config["MS_APPLICATION_ID"]
MS_CLIENT_SECRET_VALUE = config["MS_CLIENT_SECRET_VALUE"]
MS_CLIENT_SECRET_ID = config["MS_CLIENT_SECRET_ID"]
MS_OAUTH_ENDPOINT = config["MS_OAUTH_ENDPOINT"]
MS_OAUTH_TOKEN_URL = config["MS_OAUTH_TOKEN_URL"]
MS_REDIRECT_URL = config["MS_REDIRECT_URL"]
MS_RESPONSE_TYPE = config["MS_RESPONSE_TYPE"]
MS_SCOPE = config["MS_SCOPE"]
MS_GRAPH_ENDPOINT = config["MS_GRAPH_ENDPOINT"]

# GOOGLE Storage
GOOGLE_CLIENT_ID = config["GOOGLE_CLIENT_ID"]
GOOGLE_CLIENT_SECRET = config["GOOGLE_CLIENT_SECRET"]

# pCloud storage OAuth (only needed to connect pCloud as a storage destination). Defaults
# are pCloud's public OAuth hosts; leave client id/secret empty until you register an app.
PCLOUD_CLIENT_ID = config.get("PCLOUD_CLIENT_ID", "")
PCLOUD_CLIENT_SECRET = config.get("PCLOUD_CLIENT_SECRET", "")
PCLOUD_AUTH_URL = config.get("PCLOUD_AUTH_URL", "https://my.pcloud.com/oauth2/authorize")
PCLOUD_OAUTH_TOKEN_URL = config.get("PCLOUD_OAUTH_TOKEN_URL", "https://api.pcloud.com/oauth2_token")
PCLOUD_RESPONSE_TYPE = config.get("PCLOUD_RESPONSE_TYPE", "code")
PCLOUD_REDIRECT_URL = config.get("PCLOUD_REDIRECT_URL", "/api/v1/callback/pcloud")

# Basecamp source OAuth (only needed to back up Basecamp; register an app at
# https://launchpad.37signals.com/integrations). Defaults are Basecamp's public hosts.
BASECAMP_CLIENT_ID = config.get("BASECAMP_CLIENT_ID", "")
BASECAMP_CLIENT_SECRET = config.get("BASECAMP_CLIENT_SECRET", "")
BASECAMP_OAUTH_ENDPOINT = config.get(
    "BASECAMP_OAUTH_ENDPOINT", "https://launchpad.37signals.com/authorization/new"
)
BASECAMP_TOKEN_ENDPOINT = config.get(
    "BASECAMP_TOKEN_ENDPOINT", "https://launchpad.37signals.com/authorization/token"
)
BASECAMP_REDIRECT_URL = config.get("BASECAMP_REDIRECT_URL", "/api/v1/callback/basecamp")
GOOGLE_RESPONSE_TYPE = config.get("GOOGLE_RESPONSE_TYPE", "code")

# Cloud provider API endpoints (used by the server/volume snapshot integrations).
# These are public, stable API hosts with sensible defaults so cloud backups work
# out of the box; override in .env only if a provider changes its endpoint.
DIGITALOCEAN_API = config.get("DIGITALOCEAN_API", "https://api.digitalocean.com")
HETZNER_API = config.get("HETZNER_API", "https://api.hetzner.cloud")
UPCLOUD_API = config.get("UPCLOUD_API", "https://api.upcloud.com/1.3")
VULTR_API = config.get("VULTR_API", "https://api.vultr.com")
GOOGLE_COMPUTE_API = config.get("GOOGLE_COMPUTE_API", "https://compute.googleapis.com")
GOOGLE_RESOURCE_API = config.get(
    "GOOGLE_RESOURCE_API", "https://cloudresourcemanager.googleapis.com"
)

# OAuth token endpoints (only used when refreshing OAuth-based cloud connections).
DIGITALOCEAN_TOKEN_URL = config.get(
    "DIGITALOCEAN_TOKEN_URL", "https://cloud.digitalocean.com/v1/oauth/token"
)
GOOGLE_OAUTH_TOKEN_URL = config.get(
    "GOOGLE_OAUTH_TOKEN_URL", "https://oauth2.googleapis.com/token"
)

# DigitalOcean OAuth app (only needed for OAuth-based connections; Personal Access
# Token connections do not require these).
DIGITALOCEAN_APP_CLIENT_ID = config.get("DIGITALOCEAN_APP_CLIENT_ID", "")
DIGITALOCEAN_APP_CLIENT_SECRET = config.get("DIGITALOCEAN_APP_CLIENT_SECRET", "")

# OVH Public Cloud application credentials, per OVH endpoint region. Create an
# application at the matching console (ovh.com / ovhcloud.com) and set these to back
# up OVH instances/volumes.
OVH_CA_APP_KEY = config.get("OVH_CA_APP_KEY", "")
OVH_CA_APP_SECRET = config.get("OVH_CA_APP_SECRET", "")
OVH_EU_APP_KEY = config.get("OVH_EU_APP_KEY", "")
OVH_EU_APP_SECRET = config.get("OVH_EU_APP_SECRET", "")
OVH_US_APP_KEY = config.get("OVH_US_APP_KEY", "")
OVH_US_APP_SECRET = config.get("OVH_US_APP_SECRET", "")

# Celery (task queue + scheduled backups)
# Broker is RabbitMQ by default (the docker-compose stack includes it); override
# CELERY_BROKER_URL in .env for another broker.
CELERY_BROKER_URL = config.get("CELERY_BROKER_URL", "amqp://guest:guest@rabbitmq:5672//")
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "django-cache"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
# Task modules the worker must import at boot so every task is registered. These
# do not live in the conventional "<app>/tasks.py" location, so Celery's app
# autodiscovery does not find them; backups are dispatched by name via
# send_task()/chord(), which fails on an unregistered task unless listed here.
CELERY_IMPORTS = (
    "apps._tasks.helper.tasks",
    "apps._tasks.integration.aws",
    "apps._tasks.integration.aws_rds",
    "apps._tasks.integration.basecamp",
    "apps._tasks.integration.database",
    "apps._tasks.integration.digitalocean",
    "apps._tasks.integration.google_cloud",
    "apps._tasks.integration.hetzner",
    "apps._tasks.integration.lightsail",
    "apps._tasks.integration.oracle",
    "apps._tasks.integration.ovh_ca",
    "apps._tasks.integration.ovh_eu",
    "apps._tasks.integration.ovh_us",
    "apps._tasks.integration.upcloud",
    "apps._tasks.integration.vultr",
    "apps._tasks.integration.website",
    "apps._tasks.integration.wordpress",
    "apps._tasks.integration.storage.tasks",
)
# Local scheduled backups are driven by django-celery-beat's database scheduler
# (replaces the SaaS AWS EventBridge Scheduler).
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Backup run logs are kept on the container's local _storage volume (never uploaded to
# any external bucket) and pruned by the delete_old_logs task after this many days.
LOG_RETENTION_DAYS = int(config.get("LOG_RETENTION_DAYS", 30))

# Periodic maintenance fired by Celery beat. The DatabaseScheduler syncs these entries
# into django-celery-beat's PeriodicTask table on startup.
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "delete-old-logs": {
        "task": "delete_old_logs",
        "schedule": crontab(minute=0, hour=3),  # daily at 03:00 (worker timezone)
    },
}

# Task routing across the worker types (see docker-compose.yml):
#   cloud ..... API-only provider snapshots + general/misc tasks; scales horizontally
#   database .. database dumps (heavy CPU/disk); isolated so a big dump can't starve
#               file backups
#   files ..... website / wordpress / basecamp dumps (heavy CPU/disk); isolated
#   storage ... uploads each dump to the storage backends + local cleanup; scalable pool
#               (worker-storage) sharing the _storage volume with the dump workers
#   logs ...... DB log entries, Slack/Telegram/Firebase notifications, and on-disk
#               run-log retention (worker-logs)
#
# storage_upload/finalize_backup/delete_from_disk go to "storage" so they always run on a
# worker that can see the files the dump produced. Anything not listed here falls to the
# default queue, drained by the cloud worker.
CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_ROUTES = {
    # Local-disk dumps — isolated per type.
    "backup_database": {"queue": "database"},
    "backup_website": {"queue": "files"},
    "backup_wordpress": {"queue": "files"},
    "backup_basecamp": {"queue": "files"},
    # Local-disk upload + cleanup — handled by the scalable worker-storage pool.
    "storage_upload": {"queue": "storage"},
    "finalize_backup": {"queue": "storage"},
    "delete_from_disk": {"queue": "storage"},
    # Cloud/volume provider snapshots — API-only, no local disk.
    "backup_digitalocean": {"queue": "cloud"},
    "backup_hetzner": {"queue": "cloud"},
    "backup_vultr": {"queue": "cloud"},
    "backup_aws": {"queue": "cloud"},
    "backup_aws_rds": {"queue": "cloud"},
    "backup_lightsail": {"queue": "cloud"},
    "backup_google_cloud": {"queue": "cloud"},
    "backup_oracle": {"queue": "cloud"},
    "backup_upcloud": {"queue": "cloud"},
    "backup_ovh_ca": {"queue": "cloud"},
    "backup_ovh_eu": {"queue": "cloud"},
    "backup_ovh_us": {"queue": "cloud"},
    # Async snapshot status polling (re-queues itself); API-only, no local disk.
    "poll_cloud_backup": {"queue": "cloud"},
    # Log + notification pipeline (worker-logs): DB log entries, Slack/Telegram/Firebase
    # fan-out, and on-disk run-log retention.
    "send_log_to_db": {"queue": "logs"},
    "send_log_to_slack": {"queue": "logs"},
    "send_log_to_telegram": {"queue": "logs"},
    "send_to_firebase": {"queue": "logs"},
    "delete_old_logs": {"queue": "logs"},
}
