"""
Django settings for backupsheep project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import io
import json
import os
import warnings
from pathlib import Path
from urllib.parse import parse_qsl, quote, unquote, urlparse

from django.core.exceptions import ImproperlyConfigured
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
import google.auth
from dotenv import load_dotenv
from dotenv import dotenv_values

# Build paths inside the project like this: BASE_DIR / 'subdir'.
ROOT_PATH = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.dirname(os.path.dirname(__file__))

# Local working directory for in-progress backups and their logs. Backup tasks run
# with the project root as CWD (see supervisor config), so this resolves to the same
# place as the relative "_storage/" paths they use; ensure it exists.
os.makedirs(os.path.join(BASE_DIR, "_storage"), exist_ok=True)

if "BACKUPSHEEP_SECRETS" in os.environ:
    config = json.loads(os.environ.get("BACKUPSHEEP_SECRETS"))
else:
    config = {
        # Keep the sample's defaults available to PaaS deployments, where runtime
        # environment variables are injected but no .env file is mounted.
        # A real .env and then process environment always take precedence.
        **dotenv_values(os.path.join(BASE_DIR, ".env_sample")),
        **dotenv_values(os.path.join(BASE_DIR, ".env")),
        **os.environ,  # override loaded values with environment variables
    }

# Coerce env strings to real booleans: dotenv/docker env_file always yield strings, and
# a bare bool("false") is True, so a raw string can never be turned off. Treat only the
# obvious truthy spellings as on.
def _as_bool(value, default=False):
    if isinstance(value, bool):
        return value
    if value is None:
        return default
    return str(value).strip().lower() in ("1", "true", "yes", "on")


SECRET_KEY = config["DJANGO_SECRET_KEY"]
DEBUG = _as_bool(config.get("DJANGO_DEBUG", "false"))
DJANGO_SERVER = config["DJANGO_SERVER"]

# .env_sample values are merged in as defaults (see config above) so a PaaS deploy
# that forgets to set DJANGO_SECRET_KEY would otherwise boot with a publicly known
# signing key. Refuse to start a production instance in that state instead of
# running with forgeable sessions and undecryptable-credential keys.
if DJANGO_SERVER == "prod" and SECRET_KEY == "change-this-key":
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY is still the .env_sample placeholder. Set a long random "
        "value (python -c 'import secrets; print(secrets.token_urlsafe(64))') before "
        "running BackupSheep with DJANGO_SERVER=prod."
    )
# Accepts one host or a comma-separated list, e.g. "backup.example.com,www.example.com".
ALLOWED_HOSTS = [h.strip() for h in str(config["DJANGO_ALLOWED_HOSTS"]).split(",") if h.strip()]
CSRF_TRUSTED_ORIGINS = [f"{config['APP_PROTOCOL']}{config['APP_DOMAIN']}"]

# HTTPS / production hardening. Set DJANGO_HTTPS=true once this install is served over TLS
# (typically a reverse proxy that terminates HTTPS and forwards X-Forwarded-Proto). Left
# off by default so a plain-HTTP localhost/dev install isn't locked out by Secure cookies
# or an HTTP->HTTPS redirect loop.
HTTPS_ENABLED = _as_bool(config.get("DJANGO_HTTPS", "false"))
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_CONTENT_TYPE_NOSNIFF = True
# Platform health probes commonly reach the container over private HTTP even when the
# public endpoint is HTTPS. This endpoint contains no sensitive data and must remain 200.
SECURE_REDIRECT_EXEMPT = [r"^healthz/$"]
if HTTPS_ENABLED:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "rest_framework",
    "rest_framework.authtoken",
    "django.contrib.humanize",
    "django_user_agents",
    "django_filters",
    "django_celery_results",
    "django_celery_beat",
    'apps',

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Serve static files directly from gunicorn (no nginx in the container).
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_user_agents.middleware.UserAgentMiddleware",
    "utils.middleware.TimezoneMiddleware",
    # Forces a not-yet-configured install into the first-run wizard (and locks it
    # afterward). Must run before RedirectMiddleware so onboarding wins over login.
    "utils.middleware.OnboardingMiddleware",
    "utils.middleware.RedirectMiddleware",
    # Refreshes the self-hosted location's public IPs when the connection-setup
    # endpoints dropdown data is fetched (cheap path check per request).
    "utils.middleware.LocalLocationIPMiddleware",

]

ROOT_URLCONF = "backupsheep.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR + "/apps/console/_templates/",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "debug": DEBUG,
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.static",
                "django.template.context_processors.media",
                "django.template.context_processors.tz",
                "django.template.context_processors.i18n",
                "utils.context_processors.timezone",
                "utils.context_processors.site",
            ],
        },
    },
]

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "core_cache",
    }
}

WSGI_APPLICATION = "backupsheep.wsgi.application"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "apps.api.v1.utils.api_authentication.ConsoleSessionAuthentication",
        "apps.api.v1.utils.api_authentication.CustomTokenAuthentication",
    ),
    # The browsable API UI is handy in development but exposes a self-documenting,
    # form-driven interface in production, so only enable it when DEBUG is on.
    "DEFAULT_RENDERER_CLASSES": (
        ("rest_framework.renderers.JSONRenderer",)
        + (("rest_framework.renderers.BrowsableAPIRenderer",) if DEBUG else tuple())
    ),
    "EXCEPTION_HANDLER": "rest_framework.views.exception_handler",
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
    ),
}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
MIGRATION_MODULES = {"apps": "apps._migrations"}


def _database_config():
    """Build Django's PostgreSQL configuration from a URL or discrete DB_* values.

    Managed platforms conventionally provide DATABASE_URL. Docker Compose and existing
    installs keep using DB_NAME/DB_USER/DB_PASSWORD/DB_HOST/DB_PORT, so both forms stay
    supported without requiring a provider-specific settings module.
    """

    database_url = config.get("DATABASE_URL")
    if database_url:
        parsed = urlparse(str(database_url))
        if parsed.scheme not in {"postgres", "postgresql"}:
            raise ValueError("DATABASE_URL must use the postgres:// or postgresql:// scheme")

        options = dict(parse_qsl(parsed.query, keep_blank_values=True))
        if config.get("DB_SSLMODE"):
            # An explicit DB_SSLMODE is useful when a platform URL omits its TLS mode.
            options["sslmode"] = config["DB_SSLMODE"]

        return {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": unquote(parsed.path.lstrip("/")),
            "USER": unquote(parsed.username or ""),
            "PASSWORD": unquote(parsed.password or ""),
            "HOST": parsed.hostname or "",
            "PORT": str(parsed.port or 5432),
            "OPTIONS": options,
        }

    options = {}
    if config.get("DB_SSLMODE"):
        options["sslmode"] = config["DB_SSLMODE"]

    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config["DB_NAME"],
        "USER": config["DB_USER"],
        "PASSWORD": config["DB_PASSWORD"],
        "HOST": config["DB_HOST"],
        "PORT": config["DB_PORT"],
        "OPTIONS": options,
    }


DATABASES = {"default": _database_config()}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True
DATETIME_FORMAT = '%d-%m-%Y %H:%M:%S'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
)

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR + "/static/"

STATICFILES_DIRS = (
    ("console", BASE_DIR + "/apps/console/_static/console"),
)

# WhiteNoise serves collected static files from gunicorn (no nginx in the container).
# CompressedStaticFilesStorage gzips assets but does not hash filenames, so it never
# errors on a {% static %} reference whose file is missing from STATIC_ROOT.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# App Settings
APP_NAME = config["APP_NAME"]
APP_DOMAIN = config["APP_DOMAIN"]
APP_PROTOCOL = config["APP_PROTOCOL"]
APP_URL = f"{APP_PROTOCOL}{APP_DOMAIN}"

sentry_sdk.init(
    dsn=config["SENTRY_DSN"],
    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    traces_sample_rate=1.0,
    # Set profiles_sample_rate to 1.0 to profile 100%
    # of sampled transactions.
    # We recommend adjusting this value in production.
    profiles_sample_rate=1.0,
    integrations=[
        DjangoIntegration(
            transaction_style='url',
            middleware_spans=True,
            signals_spans=False,
            cache_spans=False,
        ),
    ],
    environment=DJANGO_SERVER
)

HOME_URL = "/console"
LOGIN_URL = "/login"
API_PATH = "/api/"
CONSOLE_URL = "/console"
ONBOARDING_URL = "/onboarding"

# First-run onboarding gate. Whoever completes the wizard becomes the instance admin,
# so creating the first account requires proof of infrastructure access: either this
# fixed token from the environment, or a per-install random token the app writes to
# ONBOARDING_INSTALL_TOKEN_FILE (read it with:
#   docker compose exec app cat /code/_storage/install_token
# ). Without the gate, anyone who reaches an unconfigured install over the network
# could claim the admin account before the real operator does.
ONBOARDING_INSTALL_TOKEN = config.get("ONBOARDING_INSTALL_TOKEN", "")
ONBOARDING_INSTALL_TOKEN_FILE = os.path.join(BASE_DIR, "_storage", "install_token")

LOGIN_REQUIRED_IGNORE_PATHS = [
    r'/healthz/',
    r'/login',
    r'/reset',
    r'/django-admin/',
    r'/api/',
    r'/error/',
    r'/onboarding',
    # Public team-invite acceptance page (no login required).
    r'/invite/',
]

# POSTMARK - Email Service
POSTMARK_API_KEY = config["POSTMARK_API_KEY"]
POSTMARK_DOMAIN = config["POSTMARK_DOMAIN"]
POSTMARK_EMAIL = config["POSTMARK_EMAIL"]
POSTMARK_API_URL = config["POSTMARK_API_URL"]

# AWS SES - Email Service
SES_REGION_NAME = config["SES_REGION_NAME"]
SES_REGION_ENDPOINT = config["SES_REGION_ENDPOINT"]
SES_ACCESS_KEY_ID = config["SES_ACCESS_KEY_ID"]
SES_SECRET_ACCESS_KEY = config["SES_SECRET_ACCESS_KEY"]

# MAILGUN - Email Service
MAILGUN_DOMAIN = config["MAILGUN_DOMAIN"]
MAILGUN_EMAIL = config["MAILGUN_EMAIL"]
MAILGUN_API_KEY = config["MAILGUN_API_KEY"]
MAILGUN_API_URL = config["MAILGUN_API_URL"]

# Options are postmark, mailgun and ses
EMAIL_PROVIDER = config["EMAIL_PROVIDER"]

# Slack / Telegram notification channels (only needed to connect those channels
# to an account; email notifications work without them). Create a Slack app at
# https://api.slack.com/apps for the id/secret; TELEGRAM_BOT_KEY comes from
# BotFather. Blank keeps the channels disabled.
SLACK_TOKEN_URL = config.get("SLACK_TOKEN_URL", "")
SLACK_CLIENT_ID = config.get("SLACK_CLIENT_ID", "")
SLACK_CLIENT_SECRET = config.get("SLACK_CLIENT_SECRET", "")
TELEGRAM_BOT_KEY = config.get("TELEGRAM_BOT_KEY", "")

# 'Local Storage' backup destination: root directory on this server under which the
# `local` storage backend keeps backup zips. In the Compose stack this is the
# `backup_storage` volume mounted at /backups; point BS_LOCAL_STORAGE_PATH at a bigger
# disk/NFS mount (or bind-mount over /backups) to move where backups land.
LOCAL_STORAGE_ROOT = config.get("BS_LOCAL_STORAGE_PATH", "/backups")

# Storage to be used for application logs etc. Tested with AWS S3 and Cloudflare R2
S3_ACCESS_KEY_ID = config["S3_ACCESS_KEY_ID"]
S3_SECRET_ACCESS_KEY = config["S3_SECRET_ACCESS_KEY"]
S3_STORAGE_BUCKET_NAME = config["S3_STORAGE_BUCKET_NAME"]
S3_ENDPOINT_URL = config["S3_ENDPOINT_URL"]
S3_SIGNATURE_VERSION = config["S3_SIGNATURE_VERSION"]

# Dropbox Storage - Create Dropbox App and add keys in .env file
# Learn more: https://www.dropbox.com/developers/reference/getting-started#app%20console
DROPBOX_APP_KEY = config["DROPBOX_APP_KEY"]
DROPBOX_APP_SECRET = config["DROPBOX_APP_SECRET"]


# OneDrive Storage
MS_CLIENT_ID = config["MS_CLIENT_ID"]
MS_OBJECT_ID = config["MS_OBJECT_ID"]
MS_TENANT_ID = config["MS_TENANT_ID"]
MS_APPLICATION_ID = config["MS_APPLICATION_ID"]
MS_CLIENT_SECRET_VALUE = config["MS_CLIENT_SECRET_VALUE"]
MS_CLIENT_SECRET_ID = config["MS_CLIENT_SECRET_ID"]
MS_OAUTH_ENDPOINT = config["MS_OAUTH_ENDPOINT"]
MS_OAUTH_TOKEN_URL = config["MS_OAUTH_TOKEN_URL"]
MS_REDIRECT_URL = config["MS_REDIRECT_URL"]
MS_RESPONSE_TYPE = config["MS_RESPONSE_TYPE"]
MS_SCOPE = config["MS_SCOPE"]
MS_GRAPH_ENDPOINT = config["MS_GRAPH_ENDPOINT"]

# GOOGLE Storage
GOOGLE_CLIENT_ID = config["GOOGLE_CLIENT_ID"]
GOOGLE_CLIENT_SECRET = config["GOOGLE_CLIENT_SECRET"]

# pCloud storage OAuth (only needed to connect pCloud as a storage destination). Defaults
# are pCloud's public OAuth hosts; leave client id/secret empty until you register an app.
PCLOUD_CLIENT_ID = config.get("PCLOUD_CLIENT_ID", "")
PCLOUD_CLIENT_SECRET = config.get("PCLOUD_CLIENT_SECRET", "")
PCLOUD_AUTH_URL = config.get("PCLOUD_AUTH_URL", "https://my.pcloud.com/oauth2/authorize")
PCLOUD_OAUTH_TOKEN_URL = config.get("PCLOUD_OAUTH_TOKEN_URL", "https://api.pcloud.com/oauth2_token")
PCLOUD_RESPONSE_TYPE = config.get("PCLOUD_RESPONSE_TYPE", "code")
PCLOUD_REDIRECT_URL = config.get("PCLOUD_REDIRECT_URL", "/api/v1/callback/pcloud")

# Basecamp source OAuth (only needed to back up Basecamp; register an app at
# https://launchpad.37signals.com/integrations). Defaults are Basecamp's public hosts.
BASECAMP_CLIENT_ID = config.get("BASECAMP_CLIENT_ID", "")
BASECAMP_CLIENT_SECRET = config.get("BASECAMP_CLIENT_SECRET", "")
BASECAMP_OAUTH_ENDPOINT = config.get(
    "BASECAMP_OAUTH_ENDPOINT", "https://launchpad.37signals.com/authorization/new"
)
BASECAMP_TOKEN_ENDPOINT = config.get(
    "BASECAMP_TOKEN_ENDPOINT", "https://launchpad.37signals.com/authorization/token"
)
BASECAMP_REDIRECT_URL = config.get("BASECAMP_REDIRECT_URL", "/api/v1/callback/basecamp")
GOOGLE_RESPONSE_TYPE = config.get("GOOGLE_RESPONSE_TYPE", "code")

# Cloud provider API endpoints (used by the server/volume snapshot integrations).
# These are public, stable API hosts with sensible defaults so cloud backups work
# out of the box; override in .env only if a provider changes its endpoint.
DIGITALOCEAN_API = config.get("DIGITALOCEAN_API", "https://api.digitalocean.com")
HETZNER_API = config.get("HETZNER_API", "https://api.hetzner.cloud")
UPCLOUD_API = config.get("UPCLOUD_API", "https://api.upcloud.com/1.3")
VULTR_API = config.get("VULTR_API", "https://api.vultr.com")
# Requests to Vultr must have bounded connect/read timeouts so a worker can
# recover an in-progress operation after a provider/network stall.
VULTR_API_TIMEOUT = (
    int(config.get("VULTR_API_CONNECT_TIMEOUT", 10)),
    int(config.get("VULTR_API_READ_TIMEOUT", 60)),
)
# Public-IP lookup services used to detect this server's own outbound IPv4/IPv6 for the
# self-hosted ("local") backup-server location, so users can allow-list them on their
# firewalls. Any service returning a bare IP address as the response body works.
PUBLIC_IPV4_LOOKUP_URL = config.get("PUBLIC_IPV4_LOOKUP_URL", "https://api.ipify.org")
PUBLIC_IPV6_LOOKUP_URL = config.get("PUBLIC_IPV6_LOOKUP_URL", "https://api6.ipify.org")
GOOGLE_COMPUTE_API = config.get("GOOGLE_COMPUTE_API", "https://compute.googleapis.com")
GOOGLE_RESOURCE_API = config.get(
    "GOOGLE_RESOURCE_API", "https://cloudresourcemanager.googleapis.com"
)

# OAuth token endpoints (only used when refreshing OAuth-based cloud connections).
DIGITALOCEAN_TOKEN_URL = config.get(
    "DIGITALOCEAN_TOKEN_URL", "https://cloud.digitalocean.com/v1/oauth/token"
)
GOOGLE_OAUTH_TOKEN_URL = config.get(
    "GOOGLE_OAUTH_TOKEN_URL", "https://oauth2.googleapis.com/token"
)

# DigitalOcean OAuth app (only needed for OAuth-based connections; Personal Access
# Token connections do not require these).
DIGITALOCEAN_APP_CLIENT_ID = config.get("DIGITALOCEAN_APP_CLIENT_ID", "")
DIGITALOCEAN_APP_CLIENT_SECRET = config.get("DIGITALOCEAN_APP_CLIENT_SECRET", "")

# OVH Public Cloud application credentials, per OVH endpoint region. Create an
# application at the matching console (ovh.com / ovhcloud.com) and set these to back
# up OVH instances/volumes.
OVH_CA_APP_KEY = config.get("OVH_CA_APP_KEY", "")
OVH_CA_APP_SECRET = config.get("OVH_CA_APP_SECRET", "")
OVH_EU_APP_KEY = config.get("OVH_EU_APP_KEY", "")
OVH_EU_APP_SECRET = config.get("OVH_EU_APP_SECRET", "")
OVH_US_APP_KEY = config.get("OVH_US_APP_KEY", "")
OVH_US_APP_SECRET = config.get("OVH_US_APP_SECRET", "")

# Celery (task queue + scheduled backups). BackupSheep uses RabbitMQ exclusively.
# Hosted platforms can provide RabbitMQ as individually referenced variables, which avoids
# embedding or escaping a generated password in their deployment manifests.
DEFAULT_CELERY_BROKER_URL = "amqp://guest:guest@rabbitmq:5672//"


def _resolve_celery_broker_url(values):
    """Return an AMQP URL from a complete URL or RabbitMQ connection fragments.

    Fragment variables take precedence because managed-platform deployments inject them
    at runtime while `.env_sample` supplies the Compose URL as a fallback. Credentials
    and virtual hosts are URL-encoded so generated platform secrets remain valid.
    """
    host = str(values.get("RABBITMQ_HOST") or "").strip()
    if host:
        if not (values.get("RABBITMQ_USER") and values.get("RABBITMQ_PASSWORD")):
            # guest/guest is RabbitMQ's well-known default; fine for the private
            # Compose network, dangerous for any broker reachable beyond it.
            warnings.warn(
                "RABBITMQ_HOST is set without RABBITMQ_USER/RABBITMQ_PASSWORD; "
                "falling back to the well-known guest/guest credentials. Set explicit "
                "credentials unless this broker is on a trusted private network.",
                stacklevel=2,
            )
        port = str(values.get("RABBITMQ_PORT") or "5672").strip()
        user = quote(str(values.get("RABBITMQ_USER") or "guest"), safe="")
        password = quote(str(values.get("RABBITMQ_PASSWORD") or "guest"), safe="")
        vhost = str(values.get("RABBITMQ_VHOST") or "/").strip().strip("/")
        vhost_path = quote(vhost, safe="")
        if vhost_path:
            return f"amqp://{user}:{password}@{host}:{port}/{vhost_path}"
        return f"amqp://{user}:{password}@{host}:{port}//"

    # The Heroku template provisions CloudAMQP's RabbitMQ plan, which exposes its
    # canonical AMQP URL as CLOUDAMQP_URL. Prefer it over the Compose fallback from
    # .env_sample, while still allowing an explicitly supplied RabbitMQ URL elsewhere.
    broker_url = str(
        values.get("CLOUDAMQP_URL")
        or values.get("CELERY_BROKER_URL")
        or DEFAULT_CELERY_BROKER_URL
    )
    if urlparse(broker_url).scheme not in {"amqp", "amqps"}:
        raise ValueError("RabbitMQ broker URLs must use the amqp:// or amqps:// scheme.")
    return broker_url


CELERY_BROKER_URL = _resolve_celery_broker_url(config)
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "django-cache"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
# Backup tasks perform remote side effects. A worker must acknowledge them only after
# the task has committed its provider id/status, otherwise a worker crash can lose the
# task while leaving an IN_PROGRESS row that nobody resumes. RabbitMQ redelivers late-
# acknowledged tasks when the worker connection disappears.
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_DEFAULT_DELIVERY_MODE = "persistent"
# Keep workers connected through normal broker restarts/reboots. Combined with
# RabbitMQ's persistent volume in docker-compose.yml and the DB recovery sweep,
# this prevents a transient broker outage from turning an in-progress backup into
# an orphaned row.
CELERY_BROKER_CONNECTION_RETRY = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_MAX_RETRIES = None
CELERY_BROKER_HEARTBEAT = 60
# Require RabbitMQ to confirm each persistent publication.  A confirmation can
# still be lost after broker acceptance, so the database outbox republishes the
# same task id and relies on worker-side idempotency/fencing.
CELERY_BROKER_TRANSPORT_OPTIONS = {"confirm_publish": True}
CELERY_TASK_PUBLISH_RETRY = True
CELERY_TASK_PUBLISH_RETRY_POLICY = {
    "max_retries": 3,
    "interval_start": 0,
    "interval_step": 1,
    "interval_max": 3,
}
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
# Task modules the worker must import at boot so every task is registered. These
# do not live in the conventional "<app>/tasks.py" location, so Celery's app
# autodiscovery does not find them; backups are dispatched by name via
# send_task()/chord(), which fails on an unregistered task unless listed here.
CELERY_IMPORTS = (
    "apps._tasks.helper.tasks",
    "apps._tasks.helper.maintenance",
    "apps._tasks.integration.aws",
    "apps._tasks.integration.aws_rds",
    "apps._tasks.integration.basecamp",
    "apps._tasks.integration.database",
    "apps._tasks.integration.digitalocean",
    "apps._tasks.integration.google_cloud",
    "apps._tasks.integration.hetzner",
    "apps._tasks.integration.lightsail",
    "apps._tasks.integration.lightsail_bucket",
    "apps._tasks.integration.oracle",
    "apps._tasks.integration.ovh_ca",
    "apps._tasks.integration.ovh_eu",
    "apps._tasks.integration.ovh_us",
    "apps._tasks.integration.restore",
    "apps._tasks.integration.upcloud",
    "apps._tasks.integration.vultr",
    "apps._tasks.integration.vultr_database",
    "apps._tasks.integration.website",
    "apps._tasks.integration.wordpress",
    "apps._tasks.integration.storage.tasks",
)
# Local scheduled backups are driven by BackupSheep's django-celery-beat database
# scheduler (replaces the SaaS AWS EventBridge Scheduler). The custom scheduler
# commits each occurrence and its outbox before broker publication.
CELERY_BEAT_SCHEDULER = "backupsheep.scheduler:BackupDatabaseScheduler"

# Backup run logs are kept on the container's local _storage volume (never uploaded to
# any external bucket) and pruned by the delete_old_logs task after this many days.
LOG_RETENTION_DAYS = int(config.get("LOG_RETENTION_DAYS", 30))

# A periodic recovery sweep catches tasks that were lost before late-ack redelivery
# (for example during broker/server maintenance) and stale ETA poll messages. The
# provider backup UUID/name is deterministic, so recovery can look up an already
# created remote snapshot before issuing another create request.
BACKUP_RECOVERY_STALE_SECONDS = int(
    config.get("BACKUP_RECOVERY_STALE_SECONDS", 15 * 60)
)
BACKUP_RECOVERY_BATCH_SIZE = int(config.get("BACKUP_RECOVERY_BATCH_SIZE", 100))
BACKUP_REQUEST_RETRY_SECONDS = int(
    config.get("BACKUP_REQUEST_RETRY_SECONDS", 60)
)
BACKUP_REQUEST_RETRY_MAX_SECONDS = int(
    config.get("BACKUP_REQUEST_RETRY_MAX_SECONDS", 15 * 60)
)
BACKUP_REQUEST_CLAIM_TIMEOUT_SECONDS = int(
    config.get("BACKUP_REQUEST_CLAIM_TIMEOUT_SECONDS", 5 * 60)
)
BACKUP_REQUEST_CLAIM_TIMEOUT_MAX_SECONDS = int(
    config.get("BACKUP_REQUEST_CLAIM_TIMEOUT_MAX_SECONDS", 60 * 60)
)
BACKUP_REQUEST_DISPATCH_LEASE_SECONDS = int(
    config.get("BACKUP_REQUEST_DISPATCH_LEASE_SECONDS", 60)
)
BACKUP_REQUEST_RECOVERY_BATCH_SIZE = int(
    config.get("BACKUP_REQUEST_RECOVERY_BATCH_SIZE", 100)
)
BACKUP_POLL_INTERVAL = int(config.get("BACKUP_POLL_INTERVAL", 120))
# Short, renewable leases protect long-running local dumps and chord publication.
# A worker heartbeat extends the lease; after a hard crash, recovery can safely take
# over within minutes rather than waiting for the command's multi-hour timeout.
BACKUP_WORKER_LEASE_SECONDS = int(
    config.get("BACKUP_WORKER_LEASE_SECONDS", 180)
)
BACKUP_WORKER_HEARTBEAT_SECONDS = int(
    config.get("BACKUP_WORKER_HEARTBEAT_SECONDS", 30)
)
BACKUP_DELETE_LEASE_SECONDS = int(
    config.get("BACKUP_DELETE_LEASE_SECONDS", 300)
)
BACKUP_STORAGE_LEASE_SECONDS = int(
    config.get("BACKUP_STORAGE_LEASE_SECONDS", 180)
)
BACKUP_STORAGE_HEARTBEAT_SECONDS = int(
    config.get("BACKUP_STORAGE_HEARTBEAT_SECONDS", 30)
)
RESTORE_WORKER_LEASE_SECONDS = int(
    config.get("RESTORE_WORKER_LEASE_SECONDS", 180)
)
RESTORE_WORKER_HEARTBEAT_SECONDS = int(
    config.get("RESTORE_WORKER_HEARTBEAT_SECONDS", 30)
)
RESTORE_RECOVERY_STALE_SECONDS = int(
    config.get("RESTORE_RECOVERY_STALE_SECONDS", 5 * 60)
)
RESTORE_RECOVERY_DISPATCH_LEASE_SECONDS = int(
    config.get("RESTORE_RECOVERY_DISPATCH_LEASE_SECONDS", 120)
)
RESTORE_RECOVERY_BATCH_SIZE = int(config.get("RESTORE_RECOVERY_BATCH_SIZE", 100))
# Lease the provider-create phase separately from polling. This closes the race in
# which a duplicate delivery or recovery sweep enters the same create call while the
# first worker is still waiting on the provider API.
BACKUP_CREATE_LEASE_SECONDS = int(
    config.get("BACKUP_CREATE_LEASE_SECONDS", 60 * 60)
)
# A storage upload can legitimately run much longer than the general recovery
# interval. Keep a separate claimant lease so a duplicate chord does not take over
# a healthy long-running upload and invoke the finalizer too early.
BACKUP_STORAGE_STALE_SECONDS = int(
    config.get("BACKUP_STORAGE_STALE_SECONDS", 6 * 60 * 60)
)

# Lifetime (seconds) of presigned download URLs generated for backup archives. 24h by
# default; lower it for immutable/compliance destinations where long-lived URLs weaken
# the protection story.
S3_DOWNLOAD_URL_EXPIRES = int(config.get("S3_DOWNLOAD_URL_EXPIRES", 24 * 3600))

# Paramiko and the system SSH client both require a verified host key for SSH/SFTP
# backup sources.  Keep the file under the persistent _storage volume by default so
# operators can mount a reviewed known_hosts file into the worker containers.
SSH_KNOWN_HOSTS_PATH = os.path.expanduser(
    str(config.get("SSH_KNOWN_HOSTS_PATH", os.path.join(BASE_DIR, "_storage", "ssh_known_hosts")))
)
if not os.path.isabs(SSH_KNOWN_HOSTS_PATH):
    SSH_KNOWN_HOSTS_PATH = os.path.join(BASE_DIR, SSH_KNOWN_HOSTS_PATH)

SSH_CONNECT_TIMEOUT = int(config.get("SSH_CONNECT_TIMEOUT", 15))
SSH_BANNER_TIMEOUT = int(config.get("SSH_BANNER_TIMEOUT", 15))
SSH_AUTH_TIMEOUT = int(config.get("SSH_AUTH_TIMEOUT", 15))
SSH_KEEPALIVE_SECONDS = int(config.get("SSH_KEEPALIVE_SECONDS", 30))
DATABASE_CONNECT_TIMEOUT = int(config.get("DATABASE_CONNECT_TIMEOUT", 15))
DATABASE_STATEMENT_TIMEOUT_MS = int(
    config.get("DATABASE_STATEMENT_TIMEOUT_MS", 15000)
)
DATABASE_LOCK_TIMEOUT_MS = int(config.get("DATABASE_LOCK_TIMEOUT_MS", 5000))
DATABASE_COMMAND_TIMEOUT = int(config.get("DATABASE_COMMAND_TIMEOUT", 23 * 3600))
DATABASE_VALIDATION_COMMAND_TIMEOUT = int(
    config.get("DATABASE_VALIDATION_COMMAND_TIMEOUT", 30)
)
PROVIDER_HTTP_CONNECT_TIMEOUT = float(
    config.get("PROVIDER_HTTP_CONNECT_TIMEOUT", 10)
)
PROVIDER_HTTP_READ_TIMEOUT = float(config.get("PROVIDER_HTTP_READ_TIMEOUT", 60))
PROVIDER_HTTP_MAX_TIMEOUT = float(config.get("PROVIDER_HTTP_MAX_TIMEOUT", 300))
PROVIDER_HTTP_MAX_RETRIES = int(config.get("PROVIDER_HTTP_MAX_RETRIES", 4))
PROVIDER_HTTP_MAX_POOL_CONNECTIONS = int(
    config.get("PROVIDER_HTTP_MAX_POOL_CONNECTIONS", 50)
)
PROVIDER_HTTP_BACKOFF_FACTOR = float(
    config.get("PROVIDER_HTTP_BACKOFF_FACTOR", 0.5)
)
S3_MULTIPART_THRESHOLD_BYTES = int(
    config.get("S3_MULTIPART_THRESHOLD_BYTES", 8 * 1024 * 1024)
)
S3_MULTIPART_PART_SIZE_BYTES = int(
    config.get("S3_MULTIPART_PART_SIZE_BYTES", 8 * 1024 * 1024)
)
DROPBOX_UPLOAD_CHUNK_SIZE_BYTES = int(
    config.get("DROPBOX_UPLOAD_CHUNK_SIZE_BYTES", 8 * 1024 * 1024)
)
RESTORE_MAX_ARCHIVE_MEMBERS = int(
    config.get("RESTORE_MAX_ARCHIVE_MEMBERS", 1_000_000)
)
RESTORE_MAX_UNCOMPRESSED_BYTES = int(
    config.get("RESTORE_MAX_UNCOMPRESSED_BYTES", 2 * 1024 ** 4)
)
RESTORE_MAX_COMPRESSION_RATIO = int(
    config.get("RESTORE_MAX_COMPRESSION_RATIO", 1000)
)
RESTORE_DISK_RESERVE_BYTES = int(
    config.get("RESTORE_DISK_RESERVE_BYTES", 512 * 1024 ** 2)
)

# Managed-key authentication is optional and must be configured as an explicit key
# pair by a self-hosted operator. Never advertise a built-in key whose private half
# is missing from workers. Relative paths are resolved beneath BASE_DIR so the
# persistent _storage volume can be shared by web and backup workers.
SSH_MANAGED_PRIVATE_KEY_PATH = os.path.expanduser(
    str(config.get("SSH_MANAGED_PRIVATE_KEY_PATH", ""))
)
if SSH_MANAGED_PRIVATE_KEY_PATH and not os.path.isabs(SSH_MANAGED_PRIVATE_KEY_PATH):
    SSH_MANAGED_PRIVATE_KEY_PATH = os.path.join(
        BASE_DIR, SSH_MANAGED_PRIVATE_KEY_PATH
    )
SSH_MANAGED_PUBLIC_KEY = str(config.get("SSH_MANAGED_PUBLIC_KEY", "")).strip()
# Compatibility for older deployments and code paths.
SSH_KEY_PATH = SSH_MANAGED_PRIVATE_KEY_PATH

# Periodic maintenance fired by Celery beat. The DatabaseScheduler syncs these entries
# into django-celery-beat's PeriodicTask table on startup.
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "delete-old-logs": {
        "task": "delete_old_logs",
        "schedule": crontab(minute=0, hour=3),  # daily at 03:00 (worker timezone)
    },
    # Prune old CoreLog rows from the database (see delete_old_db_logs task).
    "delete-old-db-logs": {
        "task": "delete_old_db_logs",
        "schedule": crontab(minute=30, hour=3),  # daily at 03:30 (worker timezone)
    },
    # Retry deletes that were deferred by S3 Object Lock retention/legal holds, so
    # keep_last retention resumes once the protection window expires.
    "retry-protected-storage-deletes": {
        "task": "retry_protected_storage_deletes",
        "schedule": crontab(minute=15, hour="*/6"),  # every 6 hours
    },
    # Resume backup rows whose task/poller disappeared without changing them to a
    # terminal state. This is deliberately frequent; the database lease in
    # poll_cloud_backup prevents duplicate pollers while a healthy poll is queued,
    # and the poll ETA lets the scheduled successor claim the next check.
    "resume-in-progress-backups": {
        "task": "resume_in_progress_backups",
        "schedule": 60.0,
    },
    "resume-in-progress-restores": {
        "task": "resume_in_progress_restores",
        "schedule": 60.0,
    },
    "resume-pending-backup-requests": {
        "task": "resume_pending_backup_requests",
        "schedule": 60.0,
    },
    # Bucket replication uses durable run/object leases and can resume after a
    # worker or server restart without issuing duplicate transfers.
    "sync-lightsail-bucket-replications": {
        "task": "sync_lightsail_bucket_replications",
        "schedule": 60.0,
    },
    "resume-lightsail-bucket-replications": {
        "task": "resume_lightsail_bucket_replications",
        "schedule": 60.0,
    },
    "resume-lightsail-bucket-restores": {
        "task": "resume_lightsail_bucket_restores",
        "schedule": 60.0,
    },
}

# Task routing across the worker types (see docker-compose.yml):
#   cloud ..... API-only provider snapshots + general/misc tasks; scales horizontally
#   database .. database dumps (heavy CPU/disk); isolated so a big dump can't starve
#               file backups
#   files ..... website / wordpress / basecamp dumps (heavy CPU/disk); isolated
#   storage ... uploads each dump to the storage backends + local cleanup; scalable pool
#               (worker-storage) sharing the _storage volume with the dump workers
#   logs ...... DB log entries, Slack/Telegram/Firebase notifications, and on-disk
#               run-log retention (worker-logs)
#
# storage_upload/finalize_backup/delete_from_disk go to "storage" so they always run on a
# worker that can see the files the dump produced. Anything not listed here falls to the
# default queue, drained by the cloud worker.
CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_ROUTES = {
    # Local-disk dumps — isolated per type.
    "backup_database": {"queue": "database"},
    "backup_website": {"queue": "files"},
    "backup_wordpress": {"queue": "files"},
    "backup_basecamp": {"queue": "files"},
    # Restores push data back to the source server — same per-type isolation.
    "restore_website_backup": {"queue": "files"},
    "restore_database_backup": {"queue": "database"},
    # Local-disk upload + cleanup — handled by the scalable worker-storage pool.
    "storage_upload": {"queue": "storage"},
    "finalize_backup": {"queue": "storage"},
    "delete_from_disk": {"queue": "storage"},
    # S3 lifecycle rule application + deferred Object Lock delete retries.
    "storage_aws_s3_sync_lifecycle": {"queue": "storage"},
    "retry_protected_storage_deletes": {"queue": "storage"},
    "sync_lightsail_bucket_replications": {"queue": "storage"},
    "resume_lightsail_bucket_replications": {"queue": "storage"},
    "resume_lightsail_bucket_restores": {"queue": "storage"},
    "start_lightsail_bucket_replication": {"queue": "storage"},
    "replicate_lightsail_bucket": {"queue": "storage"},
    "finalize_lightsail_bucket_replication": {"queue": "storage"},
    "restore_lightsail_bucket_replication": {"queue": "storage"},
    # Cloud/volume provider snapshots — API-only, no local disk.
    "backup_digitalocean": {"queue": "cloud"},
    "backup_hetzner": {"queue": "cloud"},
    "backup_vultr": {"queue": "cloud"},
    "backup_vultr_database": {"queue": "cloud"},
    "poll_vultr_database_backup": {"queue": "cloud"},
    "restore_vultr_database": {"queue": "cloud"},
    "poll_vultr_database_restore": {"queue": "cloud"},
    "restore_cloud_backup": {"queue": "cloud"},
    "poll_cloud_restore": {"queue": "cloud"},
    "backup_aws": {"queue": "cloud"},
    "backup_aws_rds": {"queue": "cloud"},
    "backup_lightsail": {"queue": "cloud"},
    "backup_google_cloud": {"queue": "cloud"},
    "backup_oracle": {"queue": "cloud"},
    "backup_upcloud": {"queue": "cloud"},
    "backup_ovh_ca": {"queue": "cloud"},
    "backup_ovh_eu": {"queue": "cloud"},
    "backup_ovh_us": {"queue": "cloud"},
    # Async snapshot status polling (re-queues itself); API-only, no local disk.
    "poll_cloud_backup": {"queue": "cloud"},
    "resume_in_progress_backups": {"queue": "default"},
    "resume_in_progress_restores": {"queue": "default"},
    "resume_pending_backup_requests": {"queue": "default"},
    # Log + notification pipeline (worker-logs): DB log entries, Slack/Telegram/Firebase
    # fan-out, and on-disk run-log retention.
    "send_log_to_db": {"queue": "logs"},
    "send_log_to_slack": {"queue": "logs"},
    "send_log_to_telegram": {"queue": "logs"},
    "send_to_firebase": {"queue": "logs"},
    "delete_old_logs": {"queue": "logs"},
    "delete_old_db_logs": {"queue": "logs"},
}
