# Generated by Django 6.0.5 on 2026-05-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_coredatabasebackuplegacy_corehostingbackuplegacy_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UtilAppSumoCode",
        ),
    ]
