# Generated by Django 6.0.5 on 2026-05-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_delete_utilappsumocode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coreschedule",
            name="aws_schedule_arn",
        ),
    ]
