# Generated by Django 6.0.5 on 2026-05-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0004_remove_coreschedule_aws_schedule_arn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coreauthdatabase",
            name="version",
            field=models.CharField(
                choices=[
                    ("mysql_8_0", "MySQL 8.0"),
                    ("mysql_5_7", "MySQL 5.7"),
                    ("mysql_5_6", "MySQL 5.6"),
                    ("mysql_5_5", "MySQL 5.5"),
                    ("mariadb_10_10", "MariaDB 10.10"),
                    ("mariadb_10_9", "MariaDB 10.9"),
                    ("mariadb_10_8", "MariaDB 10.8"),
                    ("mariadb_10_7", "MariaDB 10.7"),
                    ("mariadb_10_6", "MariaDB 10.6"),
                    ("mariadb_10_5", "MariaDB 10.5"),
                    ("mariadb_10_4", "MariaDB 10.4"),
                    ("mariadb_10_3", "MariaDB 10.3"),
                    ("mariadb_10_2", "MariaDB 10.2"),
                    ("mariadb_10_1", "MariaDB 10.1"),
                    ("postgres_18", "PostgreSQL 18"),
                    ("postgres_17", "PostgreSQL 17"),
                    ("postgres_16", "PostgreSQL 16"),
                    ("postgres_15", "PostgreSQL 15"),
                    ("postgres_14", "PostgreSQL 14"),
                    ("postgres_13", "PostgreSQL 13"),
                    ("postgres_12", "PostgreSQL 12"),
                    ("postgres_11", "PostgreSQL 11"),
                    ("postgres_10", "PostgreSQL 10"),
                    ("postgres_9", "PostgreSQL 9"),
                ],
                max_length=32,
            ),
        ),
    ]
