# Generated by Django 6.0.5 on 2026-05-22 10:04

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_seed_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('app_name', models.CharField(blank=True, default='', max_length=255)),
                ('app_protocol', models.CharField(blank=True, default='', max_length=16)),
                ('app_domain', models.CharField(blank=True, default='', max_length=255)),
                ('default_timezone', models.CharField(blank=True, default='', max_length=64)),
                ('email_provider', models.CharField(blank=True, default='', max_length=16)),
                ('email_credentials_encrypted', models.TextField(blank=True, default='')),
                ('setup_completed', models.BooleanField(default=False)),
                ('setup_completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_site_settings',
            },
        ),
    ]
