# Generated by Django 6.0.5 on 2026-05-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_coresitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corewebsite',
            name='backup_type',
            field=models.IntegerField(choices=[(1, 'Full v1'), (4, 'Full v2')], default=1),
        ),
    ]
