# Generated by Django 6.0.5 on 2026-05-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_alter_corewebsite_backup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreauthwebsite',
            name='verify_ssl',
            field=models.BooleanField(default=True),
        ),
    ]
