# Generated by Django 6.0.7 on 2026-07-21 13:19

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_coremember_password_reset_token_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreCloudRestore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('backup_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('params', models.JSONField(blank=True, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'In-Progress'), (3, 'Complete'), (4, 'Failed')], default=1)),
                ('error', models.TextField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restores', to='apps.corenode')),
            ],
            options={
                'db_table': 'core_cloud_restore',
            },
        ),
    ]
