# Generated by Django 6.0.7 on 2026-07-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_coreinvite_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corelog',
            name='type',
            field=models.IntegerField(choices=[(1, 'GENERIC'), (2, 'NODE'), (3, 'CONNECTION'), (4, 'BACKUP'), (5, 'MEMBER'), (6, 'SCHEDULE'), (7, 'STORAGE'), (8, 'RESTORE'), (9, 'AUTH')], default=1),
        ),
    ]
