# Generated by Django 6.0.7 on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0017_alter_corelog_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="corestorage",
            name="cold_storage_cost_usd_per_gib_month",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="corestorage",
            name="is_air_gapped",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="corestorage",
            name="retrieval_cost_usd_per_gib",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="corestorage",
            name="storage_cost_usd_per_gib_month",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="corestorageawss3",
            name="expected_bucket_owner",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="corestorageawss3",
            name="lifecycle_last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="corestorageawss3",
            name="lifecycle_storage_class",
            field=models.CharField(blank=True, choices=[("STANDARD_IA", "Standard-IA"), ("ONEZONE_IA", "One Zone-IA"), ("INTELLIGENT_TIERING", "Intelligent-Tiering"), ("GLACIER_IR", "Glacier Instant Retrieval"), ("GLACIER", "Glacier Flexible Retrieval"), ("DEEP_ARCHIVE", "Glacier Deep Archive")], default="", max_length=32),
        ),
        migrations.AddField(
            model_name="corestorageawss3",
            name="lifecycle_transition_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="corestorageawss3",
            name="object_lock_mode",
            field=models.CharField(blank=True, choices=[("GOVERNANCE", "Governance"), ("COMPLIANCE", "Compliance")], default="", max_length=16),
        ),
        migrations.AddField(
            model_name="corestorageawss3",
            name="object_lock_retain_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coreschedule",
            name="require_air_gapped_copy",
            field=models.BooleanField(default=False),
        ),
    ]
