# Generated by Django 6.0.7 on 2026-08-02

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0020_lightsail_resource_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreLightsailBucketReplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                ("modified", model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("source_bucket_name", models.CharField(max_length=1024)),
                ("source_prefix", models.CharField(blank=True, default="", max_length=1024)),
                ("source_endpoint_url", models.CharField(blank=True, default="", max_length=2048)),
                ("destination_prefix", models.CharField(blank=True, default="", max_length=1024)),
                ("include_versions", models.BooleanField(default=True)),
                ("part_size_bytes", models.PositiveBigIntegerField(default=67108864)),
                ("lease_seconds", models.PositiveIntegerField(default=900)),
                ("status", models.CharField(choices=[("active", "Active"), ("paused", "Paused"), ("disabled", "Disabled")], default="active", max_length=16)),
                ("enabled", models.BooleanField(default=True)),
                ("interval_minutes", models.PositiveIntegerField(default=60)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lightsail_bucket_replications", to="apps.coreaccount")),
                ("destination_storage", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lightsail_bucket_replications", to="apps.corestorage")),
                ("source_connection", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lightsail_bucket_replications", to="apps.coreconnection")),
            ],
            options={"db_table": "core_lightsail_bucket_replication"},
        ),
        migrations.CreateModel(
            name="CoreLightsailBucketReplicationRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                ("modified", model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("idempotency_key", models.CharField(max_length=255)),
                ("celery_task_id", models.CharField(blank=True, default="", max_length=255)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("complete", "Complete"), ("failed", "Failed"), ("cancelled", "Cancelled")], default="pending", max_length=16)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("object_count", models.PositiveBigIntegerField(default=0)),
                ("completed_count", models.PositiveBigIntegerField(default=0)),
                ("failed_count", models.PositiveBigIntegerField(default=0)),
                ("delete_marker_count", models.PositiveBigIntegerField(default=0)),
                ("bytes_transferred", models.PositiveBigIntegerField(default=0)),
                ("manifest_key", models.CharField(blank=True, default="", max_length=2048)),
                ("manifest", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("replication", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="apps.corelightsailbucketreplication")),
            ],
            options={"db_table": "core_lightsail_bucket_replication_run"},
        ),
        migrations.CreateModel(
            name="CoreLightsailBucketReplicationObject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                ("modified", model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified")),
                ("key", models.CharField(max_length=2048)),
                ("source_version_id", models.CharField(blank=True, default="", max_length=255)),
                ("is_delete_marker", models.BooleanField(default=False)),
                ("source_etag", models.CharField(blank=True, default="", max_length=512)),
                ("source_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("source_last_modified", models.DateTimeField(blank=True, null=True)),
                ("source_metadata", models.JSONField(blank=True, default=dict)),
                ("destination_key", models.CharField(max_length=2048)),
                ("destination_version_id", models.CharField(blank=True, default="", max_length=255)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("copying", "Copying"), ("complete", "Complete"), ("skipped", "Skipped"), ("delete_marker_applied", "Delete marker applied"), ("failed", "Failed")], default="pending", max_length=32)),
                ("bytes_transferred", models.PositiveBigIntegerField(default=0)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True, default="")),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="object_states", to="apps.corelightsailbucketreplicationrun")),
            ],
            options={"db_table": "core_lightsail_bucket_replication_object"},
        ),
        migrations.AddField(
            model_name="corelightsailbucketreplication",
            name="last_run",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="apps.corelightsailbucketreplicationrun"),
        ),
        migrations.CreateModel(
            name="CoreLightsailBucketRestoreRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                ("modified", model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("idempotency_key", models.CharField(max_length=255)),
                ("celery_task_id", models.CharField(blank=True, default="", max_length=255)),
                ("restore_prefix", models.CharField(blank=True, default="", max_length=1024)),
                ("target_prefix", models.CharField(blank=True, default="", max_length=1024)),
                ("destination_prefix", models.CharField(blank=True, default="", max_length=1024)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("complete", "Complete"), ("failed", "Failed"), ("cancelled", "Cancelled")], default="pending", max_length=16)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("object_count", models.PositiveBigIntegerField(default=0)),
                ("completed_count", models.PositiveBigIntegerField(default=0)),
                ("skipped_count", models.PositiveBigIntegerField(default=0)),
                ("failed_count", models.PositiveBigIntegerField(default=0)),
                ("bytes_restored", models.PositiveBigIntegerField(default=0)),
                ("completed_objects", models.JSONField(blank=True, default=list)),
                ("manifest", models.JSONField(blank=True, default=dict)),
                ("lease_owner", models.CharField(blank=True, default="", max_length=255)),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("replication", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="restore_runs", to="apps.corelightsailbucketreplication")),
                ("source_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="restore_runs", to="apps.corelightsailbucketreplicationrun")),
            ],
            options={"db_table": "core_lightsail_bucket_restore_run"},
        ),
        migrations.CreateModel(
            name="CoreLightsailBucketReplicationMultipart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                ("modified", model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified")),
                ("upload_id", models.CharField(blank=True, default="", max_length=1024)),
                ("part_size_bytes", models.PositiveBigIntegerField(default=67108864)),
                ("source_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("completed_parts", models.JSONField(blank=True, default=list)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("object_state", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="multipart", to="apps.corelightsailbucketreplicationobject")),
            ],
            options={
                "db_table": "core_lightsail_bucket_replication_multipart",
                "indexes": [models.Index(fields=["upload_id"], name="core_lights_upload__344e92_idx")],
            },
        ),
        migrations.CreateModel(
            name="CoreLightsailBucketReplicationLease",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                ("modified", model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified")),
                ("owner", models.CharField(blank=True, default="", max_length=255)),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("acquired_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("object_state", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="lease", to="apps.corelightsailbucketreplicationobject")),
            ],
            options={
                "db_table": "core_lightsail_bucket_replication_lease",
                "indexes": [
                    models.Index(fields=["expires_at"], name="core_lights_expires_8d6b9b_idx"),
                    models.Index(fields=["owner", "expires_at"], name="core_lights_owner_e38be4_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="corelightsailbucketreplicationrun",
            index=models.Index(fields=["replication", "status"], name="core_lights_replica_33dcea_idx"),
        ),
        migrations.AddIndex(
            model_name="corelightsailbucketreplicationrun",
            index=models.Index(fields=["status", "started_at"], name="core_lights_status_db1b21_idx"),
        ),
        migrations.AddConstraint(
            model_name="corelightsailbucketreplicationrun",
            constraint=models.UniqueConstraint(fields=("replication", "idempotency_key"), name="unique_lightsail_bucket_replication_run_key"),
        ),
        migrations.AddIndex(
            model_name="corelightsailbucketreplicationobject",
            index=models.Index(fields=["run", "status"], name="core_lights_run_id_c68395_idx"),
        ),
        migrations.AddIndex(
            model_name="corelightsailbucketreplicationobject",
            index=models.Index(fields=["key", "source_version_id"], name="core_lights_key_7b98f5_idx"),
        ),
        migrations.AddConstraint(
            model_name="corelightsailbucketreplicationobject",
            constraint=models.UniqueConstraint(fields=("run", "key", "source_version_id", "is_delete_marker"), name="unique_lightsail_bucket_replication_object_version"),
        ),
        migrations.AddIndex(
            model_name="corelightsailbucketreplication",
            index=models.Index(fields=["account", "status"], name="core_lights_account_058520_idx"),
        ),
        migrations.AddIndex(
            model_name="corelightsailbucketreplication",
            index=models.Index(fields=["source_bucket_name", "source_prefix"], name="core_lights_source__84f3f5_idx"),
        ),
        migrations.AddConstraint(
            model_name="corelightsailbucketreplication",
            constraint=models.UniqueConstraint(fields=("source_connection", "source_bucket_name", "source_prefix", "destination_storage", "destination_prefix"), name="unique_lightsail_bucket_replication_route"),
        ),
        migrations.AddIndex(
            model_name="corelightsailbucketrestorerun",
            index=models.Index(fields=["replication", "status"], name="core_lights_replica_849496_idx"),
        ),
        migrations.AddIndex(
            model_name="corelightsailbucketrestorerun",
            index=models.Index(fields=["lease_expires_at"], name="core_lights_lease_e_e27ee1_idx"),
        ),
        migrations.AddConstraint(
            model_name="corelightsailbucketrestorerun",
            constraint=models.UniqueConstraint(fields=("replication", "idempotency_key"), name="unique_lightsail_bucket_restore_run_key"),
        ),
    ]
