# Generated by Django 6.0.8 on 2026-09-24 03:21

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0052_repair_retired_wordpress_periodic_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128)),
                ('key_prefix', models.CharField(db_index=True, editable=False, max_length=16)),
                ('key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('scope', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='apps.coreaccount')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='apps.coremember')),
            ],
            options={
                'db_table': 'core_api_token',
                'ordering': ('-created',),
            },
        ),
    ]
